### ISSUE TITLE
Tax rates are applied as percentage and not decimal

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/api-plugin-taxes-flat-rate#2] opened 2020-05-13 10:15 UTC
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)
-->

## Issue Description
In `reaction-admin`, when you add a tax rate, the form tells you to enter the rate as a decimal. For example, 0.05 equals to a 5% tax.

However, when you create a tax rate following this rule and shop for products using this tax rate on the storefront, the tax calculation isn't actually `price * taxRate` (which it should be), but rather `price * taxRate / 100` (which would only be correct if our tax rate was a percentage to start with, i.e. `5` and not `0.05`).

## Steps to Reproduce
1. Create a tax rate following the instructions in the tax rate form
2. Create a product and assign it this tax rate
3. Add the product to a cart, go to checkout
4. Notice that the tax shown in the price breakdown is 100 times less what it should be

## Possible Solution
We need to decide whether we want the tax rates to be entered by admins as percentages or decimals. Then, either fix the form in `reaction-admin`, or fix this plugin to handle the calculation the right way.

**Comment by loan-laux** [comment] 2020-05-13 10:26
@kieckhafer since you wrote this plugin, what would be the intended behavior?

**Comment by loan-laux** [comment] 2020-05-13 17:34
I've pre-submitted a PR to merge in case the intended behavior is to work with decimals (now I know you actually call them ratios) everywhere. Feel free to close it if you'd rather keep working with integer percentages and update the field label in `reaction-admin` instead.

**Comment by kieckhafer** [comment] 2020-05-14 21:23
I believe we want the admin to enter a percentage as a whole number, so entering `5` would mean `5%`, `10` would be `10%`, etc.

Unfortunately since I did all the moving of the files into their own plugins, my name is going to be attached to everything even if I wasn't the original author (which is the case here). I did some git history checking in an old tag of the main Reaction project, and I think either Brent or Aaron were the original authors here, so I'd pass this to @aldeed to make the final call.

**Comment by aldeed** [comment] 2020-05-17 15:39
This is a duplicate of [this issue](https://github.com/reactioncommerce/reaction-admin/issues/277) in admin repo, in which I commented that changing the UI text is best since that won't break people's expectations and require a major release.

**Closed as completed by aldeed** 2020-05-17 15:39 UTC
Labels: bug, needs triage

**Comment by loan-laux** [comment] 2020-05-17 15:42
Thanks @aldeed. No idea why I hadn't found this issue. I'll PR to `reaction-admin` then.
